# Generated by Django 4.2.5 on 2023-11-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadoReserva',
            fields=[
                ('estadoReservaId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('estadoReservaNombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoReserva',
            fields=[
                ('tipoSolicitudId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('fechareserva', models.DateField()),
                ('horareserva', models.TimeField()),
                ('cantidadHermanos', models.IntegerField()),
                ('observaciones', models.CharField(max_length=5000)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('donate', models.BooleanField()),
                ('fchNacimiento', models.DateField()),
                ('imagenCarnet', models.ImageField(upload_to='carnets/')),
                ('fchCreacion', models.DateTimeField(auto_now_add=True)),
                ('fchModificacion', models.DateTimeField(auto_now=True)),
                ('estadoReservaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.estadoreserva')),
                ('tipoSolicitudId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.tiporeserva')),
            ],
        ),
    ]
