# Generated by Django 4.2.5 on 2023-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigoQr',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
