# Generated by Django 4.2.5 on 2023-11-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='tipoSolicituId',
            new_name='tipoSolicitudId',
        ),
    ]
