# Generated by Django 4.2.4 on 2023-11-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
